Fix codecov3 (#33)
* rename cache folder

* fix typo

* fix indent

* print conda info

* run tests without review

* rework github action to use cache

Used https://github.com/epassaro/cache-conda-envs/blob/main/.github/workflows/ci.yml, as described in this post; https://devpress.csdn.net/cicd/62ec6fce19c509286f41703d.html

* fix typo

---------

Co-authored-by: wietsevangerwen <41104904+wietsevangerwen@users.noreply.github.com>

diff --git a/.github/workflows/tests-conda.yml b/.github/workflows/tests-conda.yml
--- a/.github/workflows/tests-conda.yml
+++ b/.github/workflows/tests-conda.yml
@@ -2,36 +2,75 @@ name: tests
 
 on:
   pull_request:
+    # types: [review_requested, ready_for_review]
+    
+
+env:
+  CACHE_NUMBER: 0  # increase to reset cache manually
+
 
 jobs:
   run-pytests:
-    if: github.event.pull_request.draft == false
-    runs-on: windows-latest
+    strategy:
+      matrix:
+        include:
+          # - os: ubuntu-latest
+          #   label: linux-64
+          #   prefix: /usr/share/miniconda3/envs/my-env
 
-    steps:
-    - uses: actions/checkout@v2
-    - uses: conda-incubator/setup-miniconda@v2
-      with:
-        python-version: 3.9
-        # miniconda-version: "latest"
-        mamba-version: "*"
-        channels: conda-forge,defaults
-        channel-priority: true
-        activate-environment: hhnk_threedi
-        environment-file: envs\environment_test.yml
-    - name: Test
-      shell: pwsh
-      run: |
-        conda info
-        conda list
-        pip install -e .
-        pytest --cov-report term-missing --cov=hhnk_threedi_tools --cov-report=xml tests/
-    - name: Upload coverage
-      uses: codecov/codecov-action@v2
+          # - os: macos-latest
+          #   label: osx-64
+          #   prefix: /Users/runner/miniconda3/envs/my-env
 
-  fail_if_pull_request_is_draft:
-    if: github.event.pull_request.draft == true
-    runs-on: windows-latest
+          - os: windows-latest
+            label: win-64
+            prefix: C:\Miniconda3\envs\my-env
+
+    name: ${{ matrix.label }}
+    runs-on: ${{ matrix.os }}
     steps:
-    - name: Fails in order to indicate that pull request needs to be marked as ready to review and unit tests workflow needs to pass.
-      run: exit 1
+      - uses: actions/checkout@v2
+
+      - name: Setup Mambaforge
+        uses: conda-incubator/setup-miniconda@v2
+        with:
+            miniforge-variant: Mambaforge
+            miniforge-version: latest
+            activate-environment: my-env
+            use-mamba: true
+
+      - name: Set cache date
+        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
+
+      - uses: actions/cache@v2
+        with:
+          path: ${{ matrix.prefix }}
+          key: ${{ matrix.label }}-conda-${{ hashFiles('envs\environment_test.yml') }}-${{ env.CACHE_NUMBER }}
+        id: cache
+
+      - name: Update environment
+        run: mamba env update -n my-env -f envs\environment_test.yml
+        if: steps.cache.outputs.cache-hit != 'true'
+
+      - name: Test
+        shell: pwsh
+        run: |
+          conda info
+          conda list
+          pip install -e .
+          pytest --cov-report term-missing --cov=hhnk_threedi_tools --cov-report=xml tests/
+      
+      - name: Upload coverage
+        uses: codecov/codecov-action@v2
+
+      #Hopefully reduces run time; see https://github.com/conda-incubator/setup-miniconda/issues/277
+      - name: Rename conda package cache
+        shell: bash
+        run: mv "${CONDA_PKGS_DIR}" "${CONDA_PKGS_DIR}_do_not_cache"
+
+    # fail_if_pull_request_is_draft:
+    #   if: github.event.pull_request.draft == true
+    #   runs-on: windows-latest
+    #   steps:
+    #   - name: Fails in order to indicate that pull request needs to be marked as ready to review and unit tests workflow needs to pass.
+    #     run: exit 1
